default:
  image: ghcr.io/jbowdre/packer-xorriso:latest

variables:
  VAULT_ADDR: "https://vault.example.com/"
  VAULT_NAMESPACE: "example/lab"

stages:
  - build
  - deploy

renew_vault_token:
  stage: .pre
  script:
    - 'curl -s --header "X-Vault-Token:${VAULT_TOKEN}" --request POST "${VAULT_ADDR}v1/auth/token/renew-self" | grep -q auth'

build_ws2019:
  stage: build
  retry:
    max: 1
  rules:
    - if: $BUILD == "ws2019"
    - if: $BUILD == "all"
  script:
    - echo "Windows Server 2019 Packer build underway..."
    - packer init builds/windows/server/2019/
    - |
      packer build -on-error=abort -force \
      -var-file="builds/common_configs/common.pkrvars.hcl" \
      "builds/windows/server/2019/"

build_ws2022:
  stage: build
  retry:
    max: 1
  rules:
    - if: $BUILD == "ws2022"
    - if: $BUILD == "all"
  script:
    - echo "Windows Server 2022 Packer build underway..."
    - packer init builds/windows/server/2022/
    - |
      packer build -on-error=abort -force \
      -var-file="builds/common_configs/common.pkrvars.hcl" \
      "builds/windows/server/2022/"

build_ubuntu2004:
  stage: build
  retry:
    max: 1
  rules:
    - if: $BUILD == "ubuntu2004"
    - if: $BUILD == "all"
  script:
    - echo "Ubuntu 20.04 Packer build underway..."
    - packer init builds/linux/ubuntu/20-04-lts/
    - |
      packer build -on-error=abort -force \
      -var-file="builds/common_configs/common.pkrvars.hcl" \
      "builds/linux/ubuntu/20-04-lts/"

build_ubuntu2204:
  stage: build
  retry:
    max: 1
  rules:
    - if: $BUILD == "ubuntu2204"
    - if: $BUILD == "all"
  script:
    - echo "Ubuntu 22.04 Packer build underway..."
    - packer init builds/linux/ubuntu/22-04-lts/
    - |
      packer build -on-error=abort -force \
      -var-file="builds/common_configs/common.pkrvars.hcl" \
      "builds/linux/ubuntu/22-04-lts/"

build_rocky9:
  stage: build
  retry:
    max: 1
  rules:
    - if: $BUILD == "rocky9"
    - if: $BUILD == "all"
  script:
    - echo "Rocky 9 Packer build underway..."
    - packer init builds/linux/rocky/9/
    - |
      packer build -on-error=abort -force \
      -var-file="builds/common_configs/common.pkrvars.hcl" \
      "builds/linux/rocky/9/"

build_rhel9:
  stage: build
  retry:
    max: 1
  rules:
    - if: $BUILD == "rhel9"
    - if: $BUILD == "all"
  script:
    - echo "Red Hat Enterprise Linux 9 Packer build underway..."
    - packer init builds/linux/rhel/9/
    - |
      packer build -on-error=abort -force \
      -var-file="builds/common_configs/common.pkrvars.hcl" \
      "builds/linux/rhel/9/"

build_rhel8:
  stage: build
  retry:
    max: 1
  rules:
    - if: $BUILD == "rhel8"
    - if: $BUILD == "all"
  script:
    - echo "Red Hat Enterprise Linux 8 Packer build underway..."
    - packer init builds/linux/rhel/8/
    - |
      packer build -on-error=abort -force \
      -var-file="builds/common_configs/common.pkrvars.hcl" \
      "builds/linux/rhel/8/"

